num1=int(input("enter the frist number"))
num2=int(input("enter the second number"))
num3=int(input("enter the third number"))
if num1>num2 and num1>num3:
    print("frist number is greater")
if num2>num1 and num2>num3:
     print("second number is greater")
if num3>num1 and num3>num2:
      print("third number is greater")     
